version: '3.1'

services:

# Mysqldb
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springtamarin
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
      - MYSQL_ROOT_HOST= %
    volumes:
      - ./data:/var/lib/mysql

# Phpmyadmin     
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: localhost
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysqldb
      
# Elasticsearch   
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "elasticsearch:2.4.6"    
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      
# Kibana     
  kibana:
    build:
      context: ./kibana/
      dockerfile: Dockerfile
    container_name: kibana
    hostname: kibana
    image: "kibana:4.6.6"
    volumes:
      - .\config\kibana\kibana.yml:/usr/share/kibana/kibana.yml
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    environment:
      - "ELASTICSEARCH_PASSWORD=changeme"
 

# Logstatsh    
  logstash:
    build:
      context: ./logstash/
      dockerfile: Dockerfile
    container_name: logstashtest
    image: logstashtest
    links: 
      - elasticsearch    
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch 
      - mysqldb 






